[versions]
agpVersion = "9.3.2"
annotationVersion = "1.10.0"
apksigVersion = "9.3.2"
materialVersion = "1.14.0"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotationVersion" }
apksig = { module = "com.android.tools.build:apksig", version.ref = "apksigVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "agpVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }