plugins {
    id 'com.android.application'
}

android {
    compileSdk 37
    namespace 'com.apk.axmleditor'

    defaultConfig {
        applicationId "com.apk.axmleditor"
        minSdkVersion 23
        targetSdk 37
        versionCode 3
        versionName "v0.3"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation (project(':library'))
    implementation libs.apksig
    implementation libs.material
}